# Generated by Django 4.2.4 on 2023-10-02 16:57

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entreprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_societe', models.CharField(blank=True, default='Nom de la societe', max_length=100, null=True, verbose_name="Nom de l'entreprise ou de la société")),
                ('telephone', models.CharField(blank=True, default='00000000', max_length=20, null=True, verbose_name='Numéro de téléphone')),
                ('domaine_act', models.CharField(blank=True, default="Domaine d'activité", max_length=100, null=True, verbose_name="Domaine d'activité")),
                ('localite', models.CharField(blank=True, default='Localite de la societe', max_length=100, null=True, verbose_name='Localisation')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Variable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la variable')),
                ('unite_mesure', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unité de mesure de la variable')),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_section', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nom de la section')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conso.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Dispositif',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_serie', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numéro serie')),
                ('nom_lieu', models.CharField(blank=True, max_length=100, null=True, verbose_name='Le lieu où se trouve le dispositif')),
                ('source_eau', models.CharField(blank=True, max_length=100, null=True, verbose_name="Source d'eau")),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('altitude', models.FloatField(blank=True, null=True)),
                ('precision', models.FloatField(blank=True, null=True)),
                ('section', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conso.section')),
                ('variable', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conso.variable')),
            ],
        ),
        migrations.CreateModel(
            name='Depense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField(default=datetime.date(2023, 1, 1))),
                ('date_fin', models.DateField(default=datetime.date(2023, 1, 1))),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conso.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Consommation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantite', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('dispositif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conso.dispositif')),
            ],
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_debut', models.DateField(default=datetime.date(2023, 1, 1))),
                ('date_fin', models.DateField(default=datetime.date(2023, 1, 1))),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conso.entreprise')),
            ],
        ),
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intitule', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('entreprise', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='conso.entreprise')),
            ],
        ),
    ]
