# Generated by Django 4.2.4 on 2023-10-02 18:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0002_alter_consommation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommation',
            name='created_at',
            field=models.DateTimeField(default=datetime.date(2023, 8, 15)),
        ),
    ]
