# Generated by Django 4.2.4 on 2023-10-02 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0003_alter_consommation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consommation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
