# Generated by Django 4.2.4 on 2023-10-11 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0004_alter_consommation_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='montant',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
        migrations.AlterField(
            model_name='depense',
            name='montant',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
