# Generated by Django 4.2.4 on 2023-10-12 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0005_alter_budget_montant_alter_depense_montant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budget',
            name='montant',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='depense',
            name='montant',
            field=models.FloatField(default=0),
        ),
    ]
