# Generated by Django 4.2.4 on 2023-10-18 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0006_alter_budget_montant_alter_depense_montant'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='dispositif',
            unique_together={('section', 'nom_lieu')},
        ),
        migrations.AlterUniqueTogether(
            name='section',
            unique_together={('entreprise', 'nom_section')},
        ),
    ]
