# Generated by Django 4.2.4 on 2024-04-14 23:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0007_alter_dispositif_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositif',
            name='altitude',
        ),
        migrations.RemoveField(
            model_name='dispositif',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='dispositif',
            name='longitude',
        ),
        migrations.RemoveField(
            model_name='dispositif',
            name='precision',
        ),
        migrations.CreateModel(
            name='Localisation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('dispositif', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conso.dispositif')),
            ],
        ),
    ]
