# Generated by Django 4.2.4 on 2024-05-25 00:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0008_remove_dispositif_altitude_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OperationFinanciere',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_operation', models.CharField(choices=[('BUDGET', 'Budget'), ('DEPENSE', 'Dépense')], default='BUDGET', max_length=7)),
                ('montant', models.FloatField(default=0)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_ajout', models.DateTimeField(auto_now_add=True)),
                ('entreprise', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='conso.entreprise')),
            ],
        ),
        migrations.RemoveField(
            model_name='depense',
            name='entreprise',
        ),
        migrations.DeleteModel(
            name='Budget',
        ),
        migrations.DeleteModel(
            name='Depense',
        ),
    ]
