# Generated by Django 4.2.4 on 2024-05-25 01:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0009_operationfinanciere_remove_depense_entreprise_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispositif',
            name='variable',
        ),
        migrations.DeleteModel(
            name='Variable',
        ),
    ]
