# Generated by Django 4.2.4 on 2024-05-30 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0010_remove_dispositif_variable_delete_variable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='message',
            new_name='contenu',
        ),
    ]
