# Generated by Django 4.2.4 on 2024-06-27 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0012_client'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='entreprise',
        ),
        migrations.RemoveField(
            model_name='client',
            name='user',
        ),
    ]
