# Generated by Django 4.2.4 on 2024-07-01 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conso', '0014_remove_client_dispositif_client_entreprise_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='activite',
            field=models.CharField(blank=True, default='Quelle travail exercez-vous??', max_length=100, null=True, verbose_name='Le travail que vous faite'),
        ),
    ]
